config/routes.rb
Rails.application.routes.draw do
  resources :restaurants do
    resources :reviews, only: [ :new, :create ]
  end
  resources :reviews, only: [:destroy ] 
  # outside of nesting because we don't talk about reviews, we just find reviews within
  # restaurant and destroy
  # nest collection actions (those that do not need an id), don't nest member actions
  #generates only two crud actions new, create and will nest within restaurants
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy # can call any restaurant.review
  CATEGORIES = ["chinese", "italian", "japanese", "french", "belgian"]
  validates :name, :phone_number, :address, :category, presence: true
  validates :category, inclusion: { in: CATEGORIES }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true, length: { maximum: 1000,
    too_long: "%{count} characters is the maximum allowed" }
  validates :rating, presence: true
  # numericality check
  RATINGS = [0,1,2,3,4,5]
  validates :rating, numericality: {only_integer: true }, inclusion: { in: RATINGS }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index #all tasks 
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.save
    redirect_to task_path(@restaurant)
    end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  private

  def update
    @restaurant = Restaurant.find(params[:id])
    @restaurant.update(restaurant_params)
    redirect_to restaurant_path(@restaurant)
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy!
    redirect_to restaurants_path
  end

  def restaurant_params
    params.require(:task).permit(:name, :address, :category)
  end
  
  
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_restaurant, except: [:destroy] #will not find restaurant that does not exist
  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.save
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new #renders instance of new that failed to save (still in /reviews)
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy!
    redirect_to restaurant_path(@review.restaurant) #go back to restaurant
  end
  
  private

  def find_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>



  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<H1> Restaurants </H1>
<%# link_to xxxx prefix edit this!! %>
<% @restaurants.each do |restaurant| %>
<h5><%= link_to restaurant.name, restaurant_path(restaurant.id) %> 
<%= restaurant.address %>
<%= restaurant.category%>
</h5>

<%= link_to "Delete", restaurant_path(restaurant), method: :delete %>
<% end %>

app/views/restaurants/show.html.erb
<p>
<strong>Name:</strong>
<%= @restaurant.name %>
</p>

<p>
<strong>Address:</strong>
<%= @restaurant.address %>
</p>

<p>
<strong>Category:</strong>
<%= @restaurant.category %>
</p>

<p> Reviews </p>
<% @restaurant.reviews.each do |review| %>
<h5>
<%= review.content %>
<hr>
<%= review.rating %>
<%= link_to 'delete', review_path(review), method: :delete %>
<hr>
<% end %>
</h5>

<%= link_to 'Edit', edit_restaurant_path(@restaurant) %> |
<%= link_to 'Back', restaurants_path %> |
<%= link_to 'Add a new review', new_restaurant_review_path(@restaurant) %>

app/views/reviews/edit.html.erb
<%= simple_form_for [@restaurant, @review] do |f|%>
  <%= f.input :content %>
  <%= f.input :rating %>
  <%= f.submit class: 'btn-btn-primary' %>
<% end %>
<form action="" method="post"></form>

app/views/reviews/new.html.erb
<%= simple_form_for [@restaurant, @review] do |f|%>
  <%= f.input :content %>
  <%= f.input :rating %>
  <%= f.submit class: 'btn-btn-primary' %>
<% end %>
<form action="" method="post"></form>